# Generated by Django 4.1.7 on 2023-04-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imdb_id', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=200)),
                ('Poster_path', models.CharField(max_length=500)),
            ],
        ),
    ]
